import React, { useState, useEffect } from 'react';
import { Container, Row, Col, Form, Button, Card, Navbar, Nav, Badge, Modal, Alert } from 'react-bootstrap';
import jsPDF from 'jspdf';
import { PDFDocument } from 'pdf-lib';
import FileConverter from './FileConverter';
import { 
    Moon, 
    Sun, 
    FileText, 
    Merge, 
    Settings, 
    Github, 
    Mail, 
    User, 
    Send,
    Zap,
    Shield,
    Sparkles,
    LogIn,
    UserPlus,
    LogOut,
    CheckCircle
} from 'lucide-react';
import './pdftooldesign.css'; // Import the CSS file

const PDFTaskTool = () => {
    const [task, setTask] = useState('');
    const [files, setFiles] = useState([]);
    const [darkMode, setDarkMode] = useState(true);
    const [showAuthModal, setShowAuthModal] = useState(false);
    const [isLogin, setIsLogin] = useState(true);
    const [user, setUser] = useState(null);
    const [authData, setAuthData] = useState({ name: '', email: '', password: '' });
    const [alert, setAlert] = useState({ show: false, message: '', type: '' });
    const [contactData, setContactData] = useState({ name: '', email: '', message: '' });
    const [isProcessing, setIsProcessing] = useState(false);

    // Check for existing token on component mount
    useEffect(() => {
        const token = localStorage.getItem('token');
        const userData = localStorage.getItem('user');
        if (token && userData) {
            setUser(JSON.parse(userData));
        }
    }, []);

    const showAlert = (message, type = 'info') => {
        setAlert({ show: true, message, type });
        setTimeout(() => setAlert({ show: false, message: '', type: '' }), 5000);
    };

    const handleAuth = async (e) => {
        e.preventDefault();
        setIsProcessing(true);
        try {
            const endpoint = isLogin ? '/api/login' : '/api/register';
            const response = await fetch(`http://localhost:5000${endpoint}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(authData)
            });

            const data = await response.json();

            if (response.ok) {
                localStorage.setItem('token', data.token);
                localStorage.setItem('user', JSON.stringify(data.user));
                setUser(data.user);
                setShowAuthModal(false);
                setAuthData({ name: '', email: '', password: '' });
                showAlert(`Welcome ${data.user.name}!`, 'success');
            } else {
                showAlert(data.message, 'danger');
            }
        } catch (error) {
            showAlert('Authentication failed. Please try again.', 'danger');
        }
        setIsProcessing(false);
    };

    const handleLogout = () => {
        localStorage.removeItem('token');
        localStorage.removeItem('user');
        setUser(null);
        showAlert('Logged out successfully', 'info');
    };

    const handleContactSubmit = async (e) => {
        e.preventDefault();
        setIsProcessing(true);
        try {
            const response = await fetch('http://localhost:5000/api/contact', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(contactData)
            });

            if (response.ok) {
                showAlert('Message sent successfully!', 'success');
                setContactData({ name: '', email: '', message: '' });
            } else {
                showAlert('Failed to send message. Please try again.', 'danger');
            }
        } catch (error) {
            showAlert('Failed to send message. Please try again.', 'danger');
        }
        setIsProcessing(false);
    };

    const handleChange = (e) => {
        setTask(e.target.value);
    };

    const handleFileChange = (e) => {
        setFiles(e.target.files);
    };

    const generatePDF = async () => {
        if (!user) {
            showAlert('Please login to generate PDFs', 'warning');
            setShowAuthModal(true);
            return;
        }

        setIsProcessing(true);
        try {
            // Simulate processing time
            await new Promise(resolve => setTimeout(resolve, 1500));
            
            const doc = new jsPDF();
            doc.text(20, 20, 'Task List');
            doc.text(20, 30, task);
            doc.text(20, 40, `Generated by: ${user.name}`);
            doc.text(20, 50, `Date: ${new Date().toLocaleDateString()}`);
            doc.save('task.pdf');
            showAlert('PDF generated successfully!', 'success');
        } catch (error) {
            showAlert('Failed to generate PDF', 'danger');
        }
        setIsProcessing(false);
    };

    const mergePDFs = async () => {
        if (!user) {
            showAlert('Please login to merge PDFs', 'warning');
            setShowAuthModal(true);
            return;
        }

        setIsProcessing(true);
        try {
            const mergedPdf = await PDFDocument.create();
            for (const file of files) {
                const arrayBuffer = await file.arrayBuffer();
                const pdf = await PDFDocument.load(arrayBuffer);
                const copiedPages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
                copiedPages.forEach((page) => {
                    mergedPdf.addPage(page);
                });
            }
            const mergedPdfFile = await mergedPdf.save();
            const blob = new Blob([mergedPdfFile], { type: 'application/pdf' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'merged.pdf';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            showAlert('PDFs merged successfully!', 'success');
        } catch (error) {
            showAlert('Failed to merge PDFs', 'danger');
        }
        setIsProcessing(false);
    };

    const toggleDarkMode = () => {
        setDarkMode(!darkMode);
    };

    return (
        <div className={darkMode ? "bg-gradient-dark text-white min-vh-100" : "bg-gradient-light text-dark min-vh-100"}>
            {/* 3D Background Elements */}
            <div className="three-d-bg">
                <div className="floating-shape shape-1"></div>
                <div className="floating-shape shape-2"></div>
                <div className="floating-shape shape-3"></div>
                <div className="floating-shape shape-4"></div>
            </div>

            {/* Alert */}
            {alert.show && (
                <div className="alert-fixed">
                    <Alert variant={alert.type} className="shadow-lg border-0 d-flex align-items-center">
                        {alert.type === 'success' && <CheckCircle size={20} className="me-2" />}
                        {alert.message}
                    </Alert>
                </div>
            )}

            {/* Modern Navbar */}
            <Navbar 
                bg={darkMode ? "dark" : "light"} 
                variant={darkMode ? "dark" : "light"} 
                expand="lg" 
                className={`navbar-3d ${darkMode ? 'navbar-glass-dark' : 'navbar-glass-light'} sticky-top`}
            >
                <Container>
                    <Navbar.Brand href="#home" className="d-flex align-items-center fw-bold">
                        <Zap size={28} className="text-primary me-2 floating" />
                        <span className="gradient-text">ToolPro Editor</span>
                        <Badge bg="primary" className="ms-2 pulse" style={{ fontSize: '0.6rem' }}>
                            PRO
                        </Badge>
                    </Navbar.Brand>
                    <Navbar.Toggle aria-controls="basic-navbar-nav" />
                    <Navbar.Collapse id="basic-navbar-nav">
                        <Nav className="ms-auto align-items-center">
                            <Nav.Link href="#home" className="fw-semibold mx-2 nav-link-3d">
                                Home
                            </Nav.Link>
                            <Nav.Link href="#about" className="fw-semibold mx-2 nav-link-3d">
                                About
                            </Nav.Link>
                            <Nav.Link href="#contact" className="fw-semibold mx-2 nav-link-3d">
                                Contact
                            </Nav.Link>
                            {user ? (
                                <>
                                    <Nav.Link className="fw-semibold mx-2 text-primary d-flex align-items-center">
                                        <User size={16} className="me-1" />
                                        {user.name}
                                    </Nav.Link>
                                    <Button 
                                        variant="outline-danger" 
                                        onClick={handleLogout}
                                        className="ms-2 d-flex align-items-center btn-3d"
                                        size="sm"
                                    >
                                        <LogOut size={16} className="me-2" />
                                        Logout
                                    </Button>
                                </>
                            ) : (
                                <Button 
                                    variant="primary" 
                                    onClick={() => setShowAuthModal(true)}
                                    className="ms-2 d-flex align-items-center btn-3d"
                                    size="sm"
                                >
                                    <LogIn size={16} className="me-2" />
                                    Login
                                </Button>
                            )}
                            <Nav.Link href="#" className="fw-semibold mx-2 nav-link-3d">
                                <Github size={20} />
                            </Nav.Link>
                            <Button 
                                variant={darkMode ? "outline-light" : "outline-dark"} 
                                onClick={toggleDarkMode}
                                className="ms-3 d-flex align-items-center btn-3d"
                                size="sm"
                            >
                                {darkMode ? <Sun size={16} className="me-2" /> : <Moon size={16} className="me-2" />}
                                {darkMode ? "Light" : "Dark"}
                            </Button>
                        </Nav>
                    </Navbar.Collapse>
                </Container>
            </Navbar>

            {/* Auth Modal */}
            <Modal 
                show={showAuthModal} 
                onHide={() => setShowAuthModal(false)}
                centered
                className="auth-modal-3d"
                backdrop="static"
            >
                <Modal.Body className="p-0">
                    <div className={`auth-container ${darkMode ? 'dark' : 'light'}`}>
                        <div className="auth-form">
                            <div className="text-center mb-4">
                                <Zap size={48} className="text-primary mb-3 floating" />
                                <h3 className="gradient-text fw-bold">
                                    {isLogin ? 'Welcome Back' : 'Create Account'}
                                </h3>
                            </div>
                            
                            <Form onSubmit={handleAuth}>
                                {!isLogin && (
                                    <Form.Group className="mb-3">
                                        <Form.Label className="fw-semibold">Full Name</Form.Label>
                                        <Form.Control
                                            type="text"
                                            value={authData.name}
                                            onChange={(e) => setAuthData({...authData, name: e.target.value})}
                                            required
                                            className="form-control-3d rounded-pill px-3 py-2"
                                            placeholder="Enter your full name"
                                        />
                                    </Form.Group>
                                )}
                                
                                <Form.Group className="mb-3">
                                    <Form.Label className="fw-semibold">Email</Form.Label>
                                    <Form.Control
                                        type="email"
                                        value={authData.email}
                                        onChange={(e) => setAuthData({...authData, email: e.target.value})}
                                        required
                                        className="form-control-3d rounded-pill px-3 py-2"
                                        placeholder="Enter your email"
                                    />
                                </Form.Group>
                                
                                <Form.Group className="mb-4">
                                    <Form.Label className="fw-semibold">Password</Form.Label>
                                    <Form.Control
                                        type="password"
                                        value={authData.password}
                                        onChange={(e) => setAuthData({...authData, password: e.target.value})}
                                        required
                                        className="form-control-3d rounded-pill px-3 py-2"
                                        placeholder="Enter your password"
                                    />
                                </Form.Group>
                                
                                <Button 
                                    type="submit" 
                                    variant="primary" 
                                    className="w-100 mb-3 btn-3d rounded-pill py-2"
                                    size="lg"
                                    disabled={isProcessing}
                                >
                                    {isProcessing ? (
                                        <div className="loading-spinner"></div>
                                    ) : isLogin ? 'Sign In' : 'Create Account'}
                                </Button>
                            </Form>
                            
                            <div className="text-center">
                                <Button 
                                    variant="link" 
                                    onClick={() => setIsLogin(!isLogin)}
                                    className="text-decoration-none"
                                >
                                    {isLogin ? "Don't have an account? Sign up" : "Already have an account? Sign in"}
                                </Button>
                            </div>
                        </div>
                    </div>
                </Modal.Body>
            </Modal>

            {/* Hero Section */}
            <Container id="home" className="mt-5 pt-4">
                <Row className="justify-content-center text-center mb-5">
                    <Col md={10} lg={8}>
                        <div className="mb-4 hero-content">
                            <Sparkles size={64} className="text-primary mb-4 floating" />
                            <h1 className="display-4 fw-bold gradient-text mb-4 text-3d">
                                Ultimate PDF Toolkit
                            </h1>
                            <p className="lead fs-4 opacity-75 mb-4">
                                Transform, merge, and manage your documents with our powerful suite of tools
                            </p>
                            {!user && (
                                <Button 
                                    variant="primary" 
                                    onClick={() => setShowAuthModal(true)}
                                    className="rounded-pill px-5 py-3 mt-3 btn-3d"
                                    size="lg"
                                >
                                    <UserPlus size={20} className="me-2" />
                                    Get Started Free
                                </Button>
                            )}
                        </div>
                    </Col>
                </Row>

                {/* Tools Grid */}
                <Row className="g-4 justify-content-center">
                    {/* PDF Generator Card */}
                    <Col md={6} lg={4}>
                        <Card className={`h-100 card-3d tool-card ${darkMode ? 'card-glass-dark' : 'card-glass-light'}`}>
                            <Card.Body className="p-4">
                                <div className="d-flex align-items-center mb-4">
                                    <div className="icon-wrapper bg-primary bg-opacity-10 p-3 rounded-circle me-3 floating">
                                        <FileText size={24} className="text-primary" />
                                    </div>
                                    <Card.Title className="mb-0 fw-bold">PDF Generator</Card.Title>
                                </div>
                                <Form>
                                    <Form.Group className="mb-4">
                                        <Form.Label className="fw-semibold">Task Description</Form.Label>
                                        <Form.Control 
                                            type="text" 
                                            placeholder="Enter your task..." 
                                            value={task} 
                                            onChange={handleChange} 
                                            className="form-control-3d rounded-pill px-3 py-2"
                                        />
                                    </Form.Group>
                                    <div className="d-grid">
                                        <Button 
                                            variant="primary" 
                                            onClick={generatePDF}
                                            className="rounded-pill fw-semibold py-2 btn-3d"
                                            size="lg"
                                            disabled={isProcessing || !task.trim()}
                                        >
                                            {isProcessing ? 'Generating...' : 'Generate PDF'}
                                        </Button>
                                    </div>
                                </Form>
                            </Card.Body>
                        </Card>
                    </Col>

                    {/* PDF Merger Card */}
                    <Col md={6} lg={4}>
                        <Card className={`h-100 card-3d tool-card ${darkMode ? 'card-glass-dark' : 'card-glass-light'}`}>
                            <Card.Body className="p-4">
                                <div className="d-flex align-items-center mb-4">
                                    <div className="icon-wrapper bg-success bg-opacity-10 p-3 rounded-circle me-3 floating">
                                        <Merge size={24} className="text-success" />
                                    </div>
                                    <Card.Title className="mb-0 fw-bold">PDF Merger</Card.Title>
                                </div>
                                <Form>
                                    <Form.Group className="mb-4">
                                        <Form.Label className="fw-semibold">Select PDF Files</Form.Label>
                                        <Form.Control 
                                            type="file" 
                                            multiple 
                                            onChange={handleFileChange} 
                                            className="form-control-3d rounded-pill px-3 py-2"
                                            accept=".pdf"
                                        />
                                        <Form.Text className="text-muted mt-2 d-block">
                                            Select multiple PDF files to merge
                                        </Form.Text>
                                    </Form.Group>
                                    <div className="d-grid">
                                        <Button 
                                            variant="success" 
                                            onClick={mergePDFs}
                                            className="rounded-pill fw-semibold py-2 btn-3d"
                                            size="lg"
                                            disabled={isProcessing || files.length === 0}
                                        >
                                            {isProcessing ? 'Merging...' : `Merge PDFs (${files.length})`}
                                        </Button>
                                    </div>
                                </Form>
                            </Card.Body>
                        </Card>
                    </Col>

                    {/* File Converter Card */}
                    <Col md={6} lg={4}>
                        <Card className={`h-100 card-3d tool-card ${darkMode ? 'card-glass-dark' : 'card-glass-light'}`}>
                            <Card.Body className="p-4">
                                <div className="d-flex align-items-center mb-4">
                                    <div className="icon-wrapper bg-warning bg-opacity-10 p-3 rounded-circle me-3 floating">
                                        <Settings size={24} className="text-warning" />
                                    </div>
                                    <Card.Title className="mb-0 fw-bold">File Converter</Card.Title>
                                </div>
                                <FileConverter darkMode={darkMode} user={user} showAlert={showAlert} />
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>
            </Container>

            {/* About Section */}
            <Container id="about" className="mt-5 py-5">
                <Row className="justify-content-center">
                    <Col md={10} lg={8}>
                        <Card className={`card-3d ${darkMode ? 'card-glass-dark' : 'card-glass-light'}`}>
                            <Card.Body className="p-5">
                                <div className="text-center mb-5">
                                    <Shield size={64} className="text-primary mb-4 floating" />
                                    <Card.Title className="display-5 fw-bold gradient-text text-3d mb-4">
                                        About ToolPro Editor
                                    </Card.Title>
                                </div>
                                <Row className="g-4">
                                    <Col md={6}>
                                        <div className="text-center p-4">
                                            <div className="icon-wrapper bg-primary bg-opacity-10 p-4 rounded-circle d-inline-flex mb-4 floating">
                                                <Zap size={32} className="text-primary" />
                                            </div>
                                            <h5 className="fw-bold mb-3">Lightning Fast</h5>
                                            <p className="text-muted mb-0">
                                                Process your documents in seconds with our optimized tools and advanced algorithms
                                            </p>
                                        </div>
                                    </Col>
                                    <Col md={6}>
                                        <div className="text-center p-4">
                                            <div className="icon-wrapper bg-success bg-opacity-10 p-4 rounded-circle d-inline-flex mb-4 floating">
                                                <Sparkles size={32} className="text-success" />
                                            </div>
                                            <h5 className="fw-bold mb-3">Secure & Private</h5>
                                            <p className="text-muted mb-0">
                                                Your files are processed locally and never stored on our servers
                                            </p>
                                        </div>
                                    </Col>
                                </Row>
                                <Card.Text className="text-center mt-5 lead fs-6">
                                    ToolPro Editor is a cutting-edge toolkit designed to revolutionize your document workflow. 
                                    From generating professional PDFs to merging documents and converting files across formats, 
                                    we provide enterprise-grade solutions with a beautiful, intuitive interface that works 
                                    seamlessly across all your devices.
                                </Card.Text>
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>
            </Container>

            {/* Contact Section */}
            <Container id="contact" className="mt-5 py-5">
                <Row className="justify-content-center">
                    <Col md={8} lg={6}>
                        <Card className={`card-3d ${darkMode ? 'card-glass-dark' : 'card-glass-light'}`}>
                            <Card.Body className="p-5">
                                <div className="text-center mb-5">
                                    <Mail size={64} className="text-primary mb-4 floating" />
                                    <Card.Title className="display-5 fw-bold gradient-text text-3d mb-3">
                                        Get In Touch
                                    </Card.Title>
                                    <p className="text-muted fs-6">We'd love to hear from you</p>
                                </div>
                                <Form onSubmit={handleContactSubmit}>
                                    <Form.Group className="mb-4">
                                        <Form.Label className="fw-semibold">
                                            <User size={18} className="me-2" />
                                            Full Name
                                        </Form.Label>
                                        <Form.Control 
                                            type="text" 
                                            placeholder="Enter your full name" 
                                            value={contactData.name}
                                            onChange={(e) => setContactData({...contactData, name: e.target.value})}
                                            className="form-control-3d rounded-pill px-3 py-2"
                                            required
                                        />
                                    </Form.Group>
                                    <Form.Group className="mb-4">
                                        <Form.Label className="fw-semibold">
                                            <Mail size={18} className="me-2" />
                                            Email Address
                                        </Form.Label>
                                        <Form.Control 
                                            type="email" 
                                            placeholder="Enter your email" 
                                            value={contactData.email}
                                            onChange={(e) => setContactData({...contactData, email: e.target.value})}
                                            className="form-control-3d rounded-pill px-3 py-2"
                                            required
                                        />
                                    </Form.Group>
                                    <Form.Group className="mb-4">
                                        <Form.Label className="fw-semibold">Message</Form.Label>
                                        <Form.Control 
                                            as="textarea" 
                                            rows={5} 
                                            placeholder="Tell us about your project..." 
                                            value={contactData.message}
                                            onChange={(e) => setContactData({...contactData, message: e.target.value})}
                                            className="form-control-3d rounded-3 px-3 py-2"
                                            required
                                        />
                                    </Form.Group>
                                    <div className="d-grid">
                                        <Button 
                                            variant="primary" 
                                            type="submit"
                                            className="rounded-pill fw-semibold py-2 btn-3d"
                                            size="lg"
                                            disabled={isProcessing}
                                        >
                                            {isProcessing ? 'Sending...' : (
                                                <>
                                                    <Send size={18} className="me-2" />
                                                    Send Message
                                                </>
                                            )}
                                        </Button>
                                    </div>
                                </Form>
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>
            </Container>

            {/* Footer */}
            <footer className={`${darkMode ? 'bg-dark' : 'bg-light'} py-5 mt-5`}>
                <Container>
                    <Row className="align-items-center">
                        <Col md={6}>
                            <div className="d-flex align-items-center">
                                <Zap size={28} className="text-primary me-2 floating" />
                                <span className="fw-bold fs-5">ToolPro Editor</span>
                            </div>
                            <p className="text-muted mt-2 mb-0">
                                Empowering your document workflow with cutting-edge tools
                            </p>
                        </Col>
                        <Col md={6} className="text-md-end mt-3 mt-md-0">
                            <span className="text-muted">
                                © 2024 ToolPro Editor. All rights reserved.
                            </span>
                        </Col>
                    </Row>
                </Container>
            </footer>
        </div>
    );
};

export default PDFTaskTool;
